### ISSUE TITLE
Streaming audio from disk

### ISSUE THREAD

**Issue by MCHSL** [cheofusi/just_playback#1]
Would be nice to be able to play long audio files without using up a lot of memory. Cool little library btw.

**Comment by cheofusi** [comment]
Thanks. Memory becomes an issue when you change the volume to often.

**Comment by cheofusi** [comment]
The  high memory usage usually happens when the volume is changed too often. I'll improve upon it soon.

**Comment by cheofusi** [comment]
Loading audio data into python objects before forwarding these to a playback device isn't the right thing to do. So I've ditched audioread and pyaudio for miniaudio. How's the memory usage now for large files ??

**Comment by MCHSL** [comment]
sorry im getting `fatal error C1083: Cannot open include file: 'io.h': No such file or directory` and I'm not ain a state to debug anyitn

**Comment by cheofusi** [comment]
Are you on Windows ??

**Comment by MCHSL** [comment]
yeah, followed the stuff in https://stackoverflow.com/questions/40018405/cannot-open-include-file-io-h-no-such-file-or-directory and no luck unfortuanely

**Comment by cheofusi** [comment]
What I uploaded to pypi is a source distribution so you'll need to get your C/C++ compiler toolchain right.

**Comment by MCHSL** [comment]
I'll get back if I manage to fix it
