### ISSUE TITLE
Can't find file no matter what??

### ISSUE THREAD

**Issue by yoyeet961** [cheofusi/just_playback#19]
It keeps not finding my file, even though it's there.
Here is everything I tried:
playback.load_file('beep.wav')
playback.load_file('sounds\\beep.wav')
playback.load_file('sounds/beep.wav')

**Comment by yoyeet961** [comment]
Solved issue.

**Comment by cheofusi** [comment]
Did you miss the file path if I may ask ?

**Comment by yoyeet961** [comment]
> Did you miss the file path if I may ask ? That one gets me every now and then.

Lol yes I did.
