### ISSUE TITLE
Error installing just_playback

### ISSUE THREAD

**Issue by amauryjaphet** [cheofusi/just_playback#26]
I runned `pip install just_playback` and this happended

Collecting just_playback
  Using cached just_playback-0.1.7.tar.gz (504 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: cffi>=1.0.0 in c:\users\amaur\appdata\local\programs\python\python311\lib\site-packages\cffi-1.15.1-py3.11-win-amd64.egg (from just_playback) (1.15.1)
Collecting tinytag
  Using cached tinytag-1.8.1-py3-none-any.whl
Requirement already satisfied: pycparser in c:\users\amaur\appdata\local\programs\python\python311\lib\site-packages\pycparser-2.21-py3.11.egg (from cffi>=1.0.0->just_playback) (2.21)
Building wheels for collected packages: just_playback
  Building wheel for just_playback (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for just_playback (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\just_playback
      copying just_playback\ma_result.py -> build\lib.win-amd64-cpython-311\just_playback
      copying just_playback\playback.py -> build\lib.win-amd64-cpython-311\just_playback
      copying just_playback\__init__.py -> build\lib.win-amd64-cpython-311\just_playback
      running build_ext
      generating cffi module 'build\\temp.win-amd64-cpython-311\\Release\\_ma_playback.c'
      creating build\temp.win-amd64-cpython-311
      creating build\temp.win-amd64-cpython-311\Release
      building '_ma_playback' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for just_playback
Failed to build just_playback
ERROR: Could not build wheels for just_playback, which is required to install pyproject.toml-based projects

please help

**Comment by loleur362** [comment]
just edit the readme please

**Comment by amauryjaphet** [comment]
i cant :(

**Comment by amauryjaphet** [comment]
wait nvm it worked

**Comment by amauryjaphet** [comment]
> just edit the readme please

thank you so much for helping me

**Comment by amauryjaphet** [comment]
still failing

**Comment by amauryjaphet** [comment]
idk what to do

**Comment by amauryjaphet** [comment]
sadly  i need to close this issue
