### ISSUE TITLE
hangs when trying to load song in Linux

### ISSUE THREAD

**Issue by Steppenwolf86** [cheofusi/just_playback#29]
I have tried to load a song from the same dictionary both ways below on Linux Mint 21.2 Cinnamon and it just hangs. The print statements are not reached. Using Python 3.10.12 and just_playback 0.1.7. No issue with mp3 as works fine with playsound module.

```
from just_playback import Playback as Pb

pb = Pb()
song = "song.mp3"
print(pb.active, song)
pb.load_file(song)
pb.play()
print("this won't print")
```

```
from just_playback import Playback

pb = Playback("song.mp3")
print("this wont print")
```

**Comment by cheofusi** [comment]
Hi,

Does it play the song anyways? Is there any debug output from the library ?

**Comment by cheofusi** [comment]
No response so far. So closing..
