### ISSUE TITLE
pip install not working on windows

### ISSUE THREAD

**Issue by plaaosert** [cheofusi/just_playback#3]
Command `python -m pip install just_playback` throws error on Windows using Python 3.6:

`ValueError: path '/home/[absolute path]/ma_playback.c' cannot be absolute`

Attempting to install package using the local version (`python -m pip install -e "...\just_playback-main" -t
"[source_dir]"`) produces a different error:
```
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help
    
    error: option --home not recognized
```

Likely some cross-platform issue, pip version also appears to be out of date?

**Comment by cheofusi** [comment]
I've added some changes to the setup.py file. Update your package with pip install -U just_playback. Does it fix the problem ??

**Comment by plaaosert** [comment]
hey - sorry for the late response, but it installs fine now! Thanks so much for the response and fix :)
Checking now for if the package functions fine.

**Comment by plaaosert** [comment]
Works perfectly. Excellent library by the way - just what I needed and seems to be the only one that works. Thank you so much.
