### ISSUE TITLE
playback.seek(x) doesn't work

### ISSUE THREAD

**Issue by HJ959** [cheofusi/just_playback#35]
Hello again :)

I still expierence the crashing when I use resume and pause. 

So I thought perhaps if I was to keep track of playback.curr_pos when I stop. And then playback.seek(previous_duration) when I play, it would let me keep track of the latest audio file.

It didn't seem to work in my code, so I tried on its own in the interactive python terminal and alas no potato.

Am I doing something silly?

```
>>> from just_playback import Playback
>>> 
>>> playback = Playback()
>>> 
>>> playback.load_file('2a99f5b0.wav')
>>>
>>> playback.seek(3)
>>> playback.curr_pos
0
```

**Comment by PrajwalVandana** [comment]
I think you need to play first?

**Comment by HJ959** [comment]
Nailed it! It now works how I want! Woo thanks
