### ISSUE TITLE
Duration is always zero

### ISSUE THREAD

**Issue by ThiagoAlexsander** [cheofusi/just_playback#4]
The return value of "duration" is always zero. Perhaps, because "self.__ma_attrs.duration" is never set? I don't actually know if it's supposed to be populated through some other function. Additionally, "TinyTag.get('path_to_soundtrack_here').duration" populates just fine.

**Comment by cheofusi** [comment]
Thanks a lot for pointing that out. Problem has been solved.

**Comment by cheofusi** [comment]
Thanks a lot for pointing that out. Problem has been solved. You can update your installation to 0.1.4
