### ISSUE TITLE
ModuleNotFoundError: No module named '_ma_playback'

### ISSUE THREAD

**Issue by Enzogaming59430** [cheofusi/just_playback#6]
I found this error while lunching a python file
`ModuleNotFoundError: No module named '_ma_playback'`
Please respond, thank you

**Comment by Enzogaming59430** [comment]
Windows 10 insider

**Comment by cheofusi** [comment]
Does pip install the library without a hitch ??

**Comment by Enzogaming59430** [comment]
the pip installer (setup.py) was broken so i installed it manualy

**Comment by cheofusi** [comment]
Can I see the pip install error ??

**Comment by Enzogaming59430** [comment]
Ok, let me uninstall it manualy

**Comment by Enzogaming59430** [comment]
`Installing collected packages: just-playback
    Running setup.py install for just-playback ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\ecole\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Ecole\\AppData\\Local\\Temp\\pip-install-deagr_qn\\just-playback_0ac963475e9744e497549c7e34e5164c\\setup.py'"'"'; __file__='"'"'C:\\Users\\Ecole\\AppData\\Local\\Temp\\pip-install-deagr_qn\\just-playback_0ac963475e9744e497549c7e34e5164c\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Ecole\AppData\Local\Temp\pip-record-jjfdc72f\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\ecole\appdata\local\programs\python\python39\Include\just-playback'
         cwd: C:\Users\Ecole\AppData\Local\Temp\pip-install-deagr_qn\just-playback_0ac963475e9744e497549c7e34e5164c\
    Complete output (23 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\just_playback
    copying just_playback\ma_errs.py -> build\lib.win-amd64-3.9\just_playback
    copying just_playback\playback.py -> build\lib.win-amd64-3.9\just_playback
    copying just_playback\__init__.py -> build\lib.win-amd64-3.9\just_playback
    running build_ext
    generating cffi module 'build\\temp.win-amd64-3.9\\Release\\_ma_playback.c'
    creating build\temp.win-amd64-3.9
    creating build\temp.win-amd64-3.9\Release
    building '_ma_playback' extension
    creating build\temp.win-amd64-3.9\Release\build
    creating build\temp.win-amd64-3.9\Release\build\temp.win-amd64-3.9
    creating build\temp.win-amd64-3.9\Release\build\temp.win-amd64-3.9\Release
    creating build\temp.win-amd64-3.9\Release\just_playback
    creating build\temp.win-amd64-3.9\Release\just_playback\miniaudio
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DMA_NO_GENERATION=1 -Ijust_playback -Ic:\users\ecole\appdata\local\programs\python\python39\include -Ic:\users\ecole\appdata\local\programs\python\python39\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include /Tcbuild\temp.win-amd64-3.9\Release\_ma_playback.c /Fobuild\temp.win-amd64-3.9\Release\build\temp.win-amd64-3.9\Release\_ma_playback.obj
    _ma_playback.c
    c:\users\ecole\appdata\local\programs\python\python39\include\pyconfig.h(59): fatal error C1083: Impossible d'ouvrir le fichier includeÿ: 'io.h'ÿ: No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\ecole\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Ecole\\AppData\\Local\\Temp\\pip-install-deagr_qn\\just-playback_0ac963475e9744e497549c7e34e5164c\\setup.py'"'"'; __file__='"'"'C:\\Users\\Ecole\\AppData\\Local\\Temp\\pip-install-deagr_qn\\just-playback_0ac963475e9744e497549c7e34e5164c\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Ecole\AppData\Local\Temp\pip-record-jjfdc72f\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\ecole\appdata\local\programs\python\python39\Include\just-playback' Check the logs for full command output.`

Username = "Ecole"

**Comment by Enzogaming59430** [comment]
oh yes, one more thing : my computer language is english

**Comment by cheofusi** [comment]
This is a common problem windows users have with pip. See https://stackoverflow.com/a/50210015/8925535. What the just_playback distro on pypi is a source distribution, so pip needs your compiler during installation. Use the above link to make sure your C++ build tools are well setup.

**Comment by Enzogaming59430** [comment]
thanks, i will try this, i will be right back
